name: ci-applications
on:
  push:
    paths:
      - .github/workflows/ci-applications.yml
      - applications/**
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  ci-applications:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./applications
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: authenticate to acd-npm repository
        run: |
          echo "registry=https://repo.omgeving.vlaanderen.be/artifactory/api/npm/acd-npm/"  > ~/.npmrc
          echo "//repo.omgeving.vlaanderen.be/artifactory/api/npm/acd-npm/:_authToken=${{ secrets.NPM_TOKEN_DOMG_ACD_NPM }}" >> ~/.npmrc
      - name: applications - npm ci
        run: npm ci
        continue-on-error: false
      - name: applications - test
        run: npx nx test
        continue-on-error: false
      - name: applications - build
        run: npx nx build
      - name: archive alliance app
        uses: actions/upload-artifact@v3
        with:
          name: dist-alliance-app
          path: ./applications/dist
          retention-days: 30
      - name: get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: ./applications
      - name: build the pages_sub_path for beta branches
        if: contains('refs/heads/beta, refs/heads/beta-apo, refs/heads/beta-dec, refs/heads/beta-olo, refs/heads/beta-phe, refs/heads/beta-uig', github.ref)
        run: |
          pagesSubPath=${{ github.ref_name }}
          echo using $pagesSubPath as pages_sub_path
          echo "pages_sub_path=$pagesSubPath" >> $GITHUB_ENV
      - name: build the pages_sub_path for the main branch
        if: contains('refs/heads/main', github.ref)
        run: |
          pagesSubPath=${{ github.ref_name }}/${{ steps.package-version.outputs.current-version }}
          echo using $pagesSubPath as pages_sub_path
          echo "pages_sub_path=$pagesSubPath" >> $GITHUB_ENV
      - name: replace the base-href with the correct path
        if:
          # only publish on github-pages main and beta-team branches
          contains('refs/heads/main, refs/heads/beta, refs/heads/beta-apo, refs/heads/beta-dec, refs/heads/beta-olo, refs/heads/beta-phe, refs/heads/beta-uig', github.ref)
        run: |
          toReplace=$(echo href=\"/\")
          baseHref=$(echo href=\"/uig-pages/build-apps/${{ env.pages_sub_path }}/alliance/\")
          echo using $baseHref as baseHref
          sed -i'.bak' "s,$toReplace,$baseHref," ./dist/apps/alliance/index.html
      - name: replace the __UIG-VERSION__ with the new version
        if:
          # only publish on github-pages main and beta-team branches
          contains('refs/heads/main, refs/heads/beta, refs/heads/beta-apo, refs/heads/beta-dec, refs/heads/beta-olo, refs/heads/beta-phe, refs/heads/beta-uig', github.ref)
        run: |
          toReplace=__UIG-VERSION__
          newVersion=${{ steps.package-version.outputs.current-version }}
          sed -i'.bak' "s,$toReplace,$newVersion," ./dist/apps/alliance/index.html
      - name: publish on github-pages
        if:
          # only publish on github-pages main and beta-team branches
          contains('refs/heads/main, refs/heads/beta, refs/heads/beta-apo, refs/heads/beta-dec, refs/heads/beta-olo, refs/heads/beta-phe, refs/heads/beta-uig', github.ref)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./applications/dist/apps
          repository-name: milieuinfo/uig-pages
          branch: main
          target-folder: build-apps/${{ env.pages_sub_path }}
          token: ${{ secrets.PAT_UIG_PAGES }}
          clean: false
