name: ci-web-components

on:
  push:
    paths:
      - .github/workflows/ci-web-components.yml
      - web-components/**

env:
  CYPRESS_CACHE_FOLDER: cypress/cache

jobs:
  checkout-install-and-cache:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web-components
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: web-components/package-lock.json
      - name: authenticate to acd-npm repository
        run: |
          echo "registry=https://repo.omgeving.vlaanderen.be/artifactory/api/npm/acd-npm/"  > ~/.npmrc
          echo "//repo.omgeving.vlaanderen.be/artifactory/api/npm/acd-npm/:_authToken=${{ secrets.NPM_TOKEN_DOMG_ACD_NPM }}" >> ~/.npmrc
      - name: npm ci
        run: npm ci
        continue-on-error: false
      - name: cache workspace
        id: cache-workspace
        uses: actions/cache@v3
        env:
          cache-name: cache-workspace
        with:
          path: |
            ./web-components
            cypress/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.run_number }}
      - name: archive documentation
        uses: actions/upload-artifact@v3
        with:
          name: archived-documentation
          path: ./documentation
          retention-days: 30

  perform-all-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web-components
    needs: checkout-install-and-cache
    steps:
      - name: restore workspace cache
        id: cache-workspace
        uses: actions/cache@v3
        env:
          cache-name: cache-workspace
        with:
          path: |
            ./web-components
            cypress/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.run_number }}
      - name: web-components - test
        run: npx nx test
        continue-on-error: false
      - name: archive unit-test results
        uses: actions/upload-artifact@v3
        with:
          name: dist-perform-all-unit-tests
          path: ./web-components/dist
          retention-days: 30

  build-apps-libs-and-storybook:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web-components
    needs: checkout-install-and-cache
    steps:
      - name: restore workspace cache
        id: cache-workspace
        uses: actions/cache@v3
        env:
          cache-name: cache-workspace
        with:
          path: |
            ./web-components
            cypress/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.run_number }}
      - name: build apps
        run: npx nx build
      - name: build libraries
        run: npm run build:all
      - name: build storybook
        run: npx nx build-storybook storybook
      - name: archive app and lib artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-build-apps-libs-and-storybook
          path: ./web-components/dist
          retention-days: 30

  e2e-test-storybook:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1, 2, 3, 4, 5]
    defaults:
      run:
        shell: bash
        working-directory: ./web-components
    needs: checkout-install-and-cache
    steps:
      - name: restore workspace cache
        id: cache-workspace
        uses: actions/cache@v3
        env:
          cache-name: cache-workspace
        with:
          path: |
            ./web-components
            cypress/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.run_number }}
      - name: storybook - e2e-test
        run: npm run storybook:ci-test-parallel-${{ matrix.job }}
      - name: archive Storybook e2e test results
        uses: actions/upload-artifact@v3
        with:
          name: dist-e2e-test-storybook-p${{ matrix.job }}
          path: ./web-components/dist
          retention-days: 1

  e2e-report-storybook:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web-components
    needs: e2e-test-storybook
    steps:
      - name: restore workspace cache
        id: cache-workspace
        uses: actions/cache@v3
        env:
          cache-name: cache-workspace
        with:
          path: |
            ./web-components
            cypress/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.run_number }}
      - name: download artifact dist-e2e-test-storybook-p1
        uses: actions/download-artifact@v3
        with:
          name: dist-e2e-test-storybook-p1
          path: ./web-components/dist
      - name: download artifact dist-e2e-test-storybook-p2
        uses: actions/download-artifact@v3
        with:
          name: dist-e2e-test-storybook-p2
          path: ./web-components/dist
      - name: download artifact dist-e2e-test-storybook-p3
        uses: actions/download-artifact@v3
        with:
          name: dist-e2e-test-storybook-p3
          path: ./web-components/dist
      - name: download artifact dist-e2e-test-storybook-p4
        uses: actions/download-artifact@v3
        with:
          name: dist-e2e-test-storybook-p4
          path: ./web-components/dist
      - name: download artifact dist-e2e-test-storybook-p5
        uses: actions/download-artifact@v3
        with:
          name: dist-e2e-test-storybook-p5
          path: ./web-components/dist
      - name: create mochawesome report
        run: |
          mkdir dist/cypress/apps/storybook-e2e/mochawesome
          npx mochawesome-merge dist/cypress/apps/storybook-e2e/mochawesome-reports/*.json > dist/cypress/apps/storybook-e2e/mochawesome/output.json
          npx marge dist/cypress/apps/storybook-e2e/mochawesome/output.json --reportDir dist/cypress/apps/storybook-e2e/mochawesome --inline --reportFilename index.html --reportPageTitle "Storybook e2e tests" --reportTitle "UIG Webcomponents - Storybook e2e tests"
      - name: archive Storybook e2e test results
        uses: actions/upload-artifact@v3
        with:
          name: dist-e2e-test-storybook
          path: ./web-components/dist
          retention-days: 30

  publish-apps-and-documentation:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web-components
    needs: [perform-all-unit-tests, build-apps-libs-and-storybook, e2e-report-storybook]
    steps:
      # github-pages-deploy-action gives an error when 'not in a git directory'
      # -> so a checkout instead of a 'restore workspace cache'
      - uses: actions/checkout@v3
      - name: get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: ./web-components
      - name: download artifacts
        uses: actions/download-artifact@v3
      - name: output the build result path
        run: echo "the build results (dist folders) are available at /build-apps/${{ github.ref_name }}/${{ steps.package-version.outputs.current-version}}"
#      - name: publish dist folder on github-pages
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          folder: web-components/dist
#          repository-name: milieuinfo/uig-pages
#          branch: main
#          target-folder: build-github/${{ github.ref_name }}/web-components/${{ github.run_number }}
#          token: ${{ secrets.PAT_UIG_PAGES }}
      - name: publish Exhibit on github-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist-build-apps-libs-and-storybook/apps/exhibit
          repository-name: milieuinfo/uig-pages
          branch: main
          target-folder: /build-apps/${{ github.ref_name }}/${{ steps.package-version.outputs.current-version}}/exhibit
          token: ${{ secrets.PAT_UIG_PAGES }}
      - name: publish Storybook on github-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist-build-apps-libs-and-storybook/apps/storybook
          repository-name: milieuinfo/uig-pages
          branch: main
          target-folder: /build-apps/${{ github.ref_name }}/${{ steps.package-version.outputs.current-version}}/storybook
          token: ${{ secrets.PAT_UIG_PAGES }}
      - name: publish documentation on github-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: archived-documentation
          repository-name: milieuinfo/uig-pages
          branch: main
          target-folder: /build-apps/${{ github.ref_name }}/${{ steps.package-version.outputs.current-version}}/documentation
          token: ${{ secrets.PAT_UIG_PAGES }}
